name: Demo Workflow Manual

on:
  workflow_dispatch:
    inputs:
      mensaje:
        description: "Mensaje que se imprimirá por consola"
        required: true
        default: "Hola desde GitHub Actions"
        type: string

jobs:
  print-message:
    name: Imprimir mensaje
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje recibido
        run: echo "Mensaje recibido => ${{ github.event.inputs.mensaje }}"
